apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    helm:
      version: v3
      valueFiles:
      - values.yaml
    repoURL: file:///Users/lalmeida1/dev/git/kube-tests
    targetRevision: HEAD
    path: argocd/external-secrets/deploy/charts/external-secrets

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  ignoreDifferences:
  - group: "*"
    kind: "*"
    managedFieldsManagers:
    - external-secrets

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
