name: gitops-actions
on: [push]
jobs:
  publish_twitter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Find new files
        run: |
          git log --diff-filter=A --name-only --oneline HEAD -1
